eval:
	python3 evaluator.py ../add.para

hello:
	python3 parser.py ../printHello.para

cond:
	python3 parser.py ../conditional.para

sort:
	python3 parser.py ../bubblesort.para

loops:
	python3 parser.py ../loops.para

clean:
	rm *.dot
	rm *.png