hello: parser.py
	python3 parser.py ../printHello.para

cond: parser.py
	python3 parser.py ../conditional.para

sort: parser.py
	python3 parser.py ../bubblesort.para

loops: parser.py
	python3 parser.py ../loops.para

clean:
	rm *.dot
	rm *.png