make hello: parser.py
	python3 parser.py ../printHello.para

make cond: parser.py
	python3 parser.py ../conditional.para

make sort: parser.py
	python3 parser.py ../bubblesort.para

make loops: parser.py
	python3 parser.py ../loops.para