eval:
	python3 -B evaluator.py ../add.para

hello:
	python3 -B parser.py ../printHello.para

cond:
	python3 -B parser.py ../conditional.para

sort:
	python3 -B parser.py ../bubblesort.para

loops:
	python3 -B parser.py ../loops.para

test:
	python3 -B tests.py -v

clean:
	rm *.dot
	rm *.png