add:
	python3 -B evaluator.py ../add.para

cond2:
	python3 -B evaluator.py ../paragraph-code/cond2.para

while:
	python3 -B evaluator.py ../paragraph-code/while.para

hello:
	python3 -B evaluator.py ../printHello.para

cond:
	python3 -B evaluator.py ../conditional.para

sort:
	python3 -B evaluator.py ../bubblesort.para

loops:
	python3 -B evaluator.py ../loops.para

test:
	python3 -B tests.py -v

clean:
	rm *.dot
	rm *.png